### ISSUE TITLE
Sorry, but don`t work

### ISSUE THREAD

**Issue by willy-wonka-git** [claustres/quasar-feathers-tutorial#12]
Download your package and run npm dev. It work without quasar modules, only api. How to run quasar front-end?

**Comment by claustres** [comment]
Hi, thanks for your feedback but you need to be more specific if you want some help. Eg what are the error messages ? What do you mean by "*It work without quasar modules, only api*" ? Or which step of the fast install procedure https://github.com/claustres/quasar-feathers-tutorial#disclaimer actually fails ?

**Comment by willy-wonka-git** [comment]
**Thanks for answer**. 
I run under VSCode "**npm dev - api**" and see localhost:8081 only feathers answers "Page Not Found"/ "Need auth" for any page. Want to see any quasar forms, but can`t. 

"**npm quasar dev -t mat -m pwa**" was in error... but now work! :)

I recomend to add that script/command in "package.json" for clarity.

**Comment by claustres** [comment]
`npm run dev` in the *api* folder will run the API server on port 8081, there is no HTML page to be seen here, that's the reason why you only have 404 and it is expected behavior. If you try to reach the API by opening in your browser eg `http://localhost:8081/users` you will see a 401 page because you need a token.

Running `quasar dev` in the root folder then launches the frontend on port 8080. You can see the app by opening in your browser `http://localhost:8080`.

Added the Quasar CLI install command in README because it is required for previous command to work.
