### ISSUE TITLE
Can we replace all 3 pacakges with one package ?

### ISSUE THREAD

**Issue by bujji1** [claustres/quasar-feathers-tutorial#5]
Thanks a lot for this code and for the tutorial    . I really appreciate for this one 

The below one is not an issue, but just a **question** 
I am looking at the package.json file and got a question with the below packages 
```
 "feathers": "^2.1.4",
  "feathers-authentication-client": "^0.3.2",
  "feathers-hooks": "^2.0.1",
```

I think we can replace all three with one package 
`//unpkg.com/feathers-client@^2.0.0-pre.1/dist/feathers.js ` ( from feathers documentation this contains all the above ) 
For details , please search for "The Feathers client from the frontend chapter already has authentication"
https://docs.feathersjs.com/guides/chat/authentication.html

**Also one small suggestion** 

May be better creating two folders one for client and another for server to logically separate them . Now the client code has server code in separate directory .

Thank You

**Comment by claustres** [comment]
Thanks for your compliments.

Regarding https://github.com/feathersjs/feathers-client it is specifically built to be used in the browser or with other module loaders that don't support NPM. Under the hood it simply "includes" other packages https://github.com/feathersjs/feathers-client/blob/master/src/client.js so it seems to be an unnecessary layer in this case.

About the folder separation this could be definitely possible however we will loose something IMHO:
1. having a root `package.json` that could contain all the commands to build/run the entire project, including the API part. I did not included an example in the tutorial but it could be interesting.
2. having an autonomous global package you can move wherever you'd like. If you have 2 separate folders you might believe they are completely independent of each other but that's actually not the case because of the internal references from the API part to the client (in the config file).

**Comment by bujji1** [comment]
Thanks for your quick reply . That clears all my questions .
Regards
